In [ ]:
import numpy as np 
import pandas as pd 
import datetime as dt

In [ ]:
# Python program to explain time.monotonic() method
 
# importing time module
import time
 
# Get the value of
# a monotonic clock at the
# beginning of the process
# using time.monotonic() method
start = time.monotonic()
 
# print the value of
# the monotonic clock
print("At the beginning of the process")
print("Value of the monotonic clock (in fractional seconds):", start)

In [ ]:


#periods = []

#period_start = tstart
#while period_start < tend:
   # period_end = min(period_start + interval, tend)
   # periods.append((period_start, period_end))
  #  period_start = period_end

#print(periods)
tstart

In [ ]:
slice1 = dt.timedelta(seconds=600)
slice2 = dt.timedelta(seconds=300)
slice3 = dt.timedelta(seconds=1200)
slice4 = dt.timedelta(seconds=900)
slice5 = dt.timedelta(seconds=600)
print(slice1)

#interval = dt.timedelta(seconds=3600)

In [ ]:
import _thread

In [ ]:
import threading

def printit():
  threading.Timer(5.0, printit).start()
  print("Hello, World!")

printit()

In [ ]:
df = pd.DataFrame(index=range(3600),columns=range(5))

In [ ]:
df

In [ ]:
def tabl(t,alarm):

In [ ]:
from threading import Timer
def hello():
    print("hhhh, world")

t = Timer(30.0, hello,L)
t.start()  # after 30 seconds, "hello, world" will be printedfrom threading import

# Importation du csv

In [1]:
import numpy as np 
import pandas as pd 
import datetime as dt

In [2]:
df = pd.read_csv(r'C:\Users\a888935\OneDrive - Atos\Documents\Doc_Alstom\alarms.csv')
df = pd.DataFrame(df)
# Sort DataFrame by date column
df.sort_values(by='ACTIVETIME', inplace = True)
df

,CALCULATIONTYPE,MESSAGE,ALARMTYPE,SERVERNODE,ACKCOMMENT,BTAVAILABILITYLOGSID,EVENTTIME,ACTIVETIME,PRIORITY,CONDITIONACTIVE,STATUS,COMMENTS,Route,Location,CHARGEABLE,BTAVAILABILITYALARMSID,GRACEPERIOD,GRACEPERIODUNIT
1,FLEET,Battery Charger Failure Cleared,VEH,3,2,2060070,2021-05-06T01:18:16Z,2021-05-06T01:12:12Z,2,False,NaN,NaN,NaN,NaN,1,747,260,SECONDS
8,FLEET,LVPS Line Failure Cleared,VEH,3,2,2060069,2021-05-06T01:18:16Z,2021-05-06T01:12:12Z,2,False,NaN,NaN,NaN,NaN,1,4511,260,SECONDS
6,FLEET,LVPS Line Failure Cleared,VEH,2,2,2060076,2021-05-06T01:18:12Z,2021-05-06T01:12:16Z,2,False,NaN,NaN,NaN,NaN,1,4497,260,SECONDS
12,FLEET,Train in Full Manual Mode Cleared,VEH,1,2,2059912,2021-05-06T01:21:23Z,2021-05-06T01:13:18Z,2,False,NaN,NaN,NaN,NaN,1,8871,260,SECONDS
3,FLEET,Emergency Brake Trainline Deenergized VATC Cle...,VEH,1,8,2058722,2021-05-06T01:46:12Z,2021-05-06T01:15:28Z,1,False,NaN,NaN,NaN,NaN,1,3003,260,SECONDS
5,FLEET,Inaccurate Station Stop Short Cleared,VEH,1,2,2058899,2021-05-06T01:43:05Z,2021-05-06T01:27:25Z,2,False,NaN,NaN,NaN,NaN,1,3809,260,SECONDS
10,FLEET,Train Failed to Arrive Cleared,TRN,TRN4,225,2058641,2021-05-06T01:47:35Z,2021-05-06T01:41:38Z,2,False,NaN,NaN,NaN,NaN,1,23057,260,SECONDS
2,FLEET,Emergency Brake Trainline Deenergized VATC Cle...,VEH,1,4,2053623,2021-05-06T04:59:58Z,2021-05-06T01:48:51Z,1,False,NaN,NaN,NaN,NaN,1,2999,260,SECONDS
4,FLEET,Inaccurate Station Stop Short Cleared,VEH,1,2,2053629,2021-05-06T04:59:54Z,2021-05-06T01:58:25Z,2,False,NaN,NaN,NaN,NaN,1,3809,260,SECONDS
11,FLEET,Train Failed to Arrive Cleared,TRN,TRN7,1,2057424,2021-05-06T02:26:56Z,2021-05-06T02:22:27Z,2,False,NaN,NaN,NaN,NaN,1,23335,260,SECONDS
14,SERVICE MODE,Unscheduled Stop Cleared,VEH,1,7,2057503,2021-05-06T02:23:34Z,2021-05-06T02:22:48Z,1,False,NaN,NaN,NaN,NaN,1,11332,1,HEADWAY
0,FLEET,Battery Charger Failure Cleared,VEH,3,12,2056902,2021-05-06T02:51:47Z,2021-05-06T02:47:22Z,2,False,NaN,NaN,NaN,NaN,1,743,260,SECONDS
7,FLEET,LVPS Line Failure Cleared,VEH,3,12,2056901,2021-05-06T02:51:47Z,2021-05-06T02:47:22Z,2,False,NaN,NaN,NaN,NaN,1,4507,260,SECONDS
9,FLEET,Summary Doors Failed to Close Cleared,VEH,1,12,2056759,2021-05-06T02:55:31Z,2021-05-06T02:49:33Z,2,False,NaN,NaN,NaN,NaN,1,23052,260,SECONDS
13,SERVICE MODE,Unscheduled Stop Cleared,VEH,1,3,2054139,2021-05-06T04:38:25Z,2021-05-06T04:38:07Z,1,False,NaN,NaN,NaN,NaN,1,11328,1,HEADWAY

In [3]:
df

,CALCULATIONTYPE,MESSAGE,ALARMTYPE,SERVERNODE,ACKCOMMENT,BTAVAILABILITYLOGSID,EVENTTIME,ACTIVETIME,PRIORITY,CONDITIONACTIVE,STATUS,COMMENTS,Route,Location,CHARGEABLE,BTAVAILABILITYALARMSID,GRACEPERIOD,GRACEPERIODUNIT
1,FLEET,Battery Charger Failure Cleared,VEH,3,2,2060070,2021-05-06T01:18:16Z,2021-05-06T01:12:12Z,2,False,NaN,NaN,NaN,NaN,1,747,260,SECONDS
8,FLEET,LVPS Line Failure Cleared,VEH,3,2,2060069,2021-05-06T01:18:16Z,2021-05-06T01:12:12Z,2,False,NaN,NaN,NaN,NaN,1,4511,260,SECONDS
6,FLEET,LVPS Line Failure Cleared,VEH,2,2,2060076,2021-05-06T01:18:12Z,2021-05-06T01:12:16Z,2,False,NaN,NaN,NaN,NaN,1,4497,260,SECONDS
12,FLEET,Train in Full Manual Mode Cleared,VEH,1,2,2059912,2021-05-06T01:21:23Z,2021-05-06T01:13:18Z,2,False,NaN,NaN,NaN,NaN,1,8871,260,SECONDS
3,FLEET,Emergency Brake Trainline Deenergized VATC Cle...,VEH,1,8,2058722,2021-05-06T01:46:12Z,2021-05-06T01:15:28Z,1,False,NaN,NaN,NaN,NaN,1,3003,260,SECONDS
5,FLEET,Inaccurate Station Stop Short Cleared,VEH,1,2,2058899,2021-05-06T01:43:05Z,2021-05-06T01:27:25Z,2,False,NaN,NaN,NaN,NaN,1,3809,260,SECONDS
10,FLEET,Train Failed to Arrive Cleared,TRN,TRN4,225,2058641,2021-05-06T01:47:35Z,2021-05-06T01:41:38Z,2,False,NaN,NaN,NaN,NaN,1,23057,260,SECONDS
2,FLEET,Emergency Brake Trainline Deenergized VATC Cle...,VEH,1,4,2053623,2021-05-06T04:59:58Z,2021-05-06T01:48:51Z,1,False,NaN,NaN,NaN,NaN,1,2999,260,SECONDS
4,FLEET,Inaccurate Station Stop Short Cleared,VEH,1,2,2053629,2021-05-06T04:59:54Z,2021-05-06T01:58:25Z,2,False,NaN,NaN,NaN,NaN,1,3809,260,SECONDS
11,FLEET,Train Failed to Arrive Cleared,TRN,TRN7,1,2057424,2021-05-06T02:26:56Z,2021-05-06T02:22:27Z,2,False,NaN,NaN,NaN,NaN,1,23335,260,SECONDS
14,SERVICE MODE,Unscheduled Stop Cleared,VEH,1,7,2057503,2021-05-06T02:23:34Z,2021-05-06T02:22:48Z,1,False,NaN,NaN,NaN,NaN,1,11332,1,HEADWAY
0,FLEET,Battery Charger Failure Cleared,VEH,3,12,2056902,2021-05-06T02:51:47Z,2021-05-06T02:47:22Z,2,False,NaN,NaN,NaN,NaN,1,743,260,SECONDS
7,FLEET,LVPS Line Failure Cleared,VEH,3,12,2056901,2021-05-06T02:51:47Z,2021-05-06T02:47:22Z,2,False,NaN,NaN,NaN,NaN,1,4507,260,SECONDS
9,FLEET,Summary Doors Failed to Close Cleared,VEH,1,12,2056759,2021-05-06T02:55:31Z,2021-05-06T02:49:33Z,2,False,NaN,NaN,NaN,NaN,1,23052,260,SECONDS
13,SERVICE MODE,Unscheduled Stop Cleared,VEH,1,3,2054139,2021-05-06T04:38:25Z,2021-05-06T04:38:07Z,1,False,NaN,NaN,NaN,NaN,1,11328,1,HEADWAY

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15 entries, 1 to 13
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CALCULATIONTYPE         15 non-null     object
 1   MESSAGE                 15 non-null     object
 2   ALARMTYPE               15 non-null     object
 3   SERVERNODE              15 non-null     object
 4   ACKCOMMENT              15 non-null     int64
 5   BTAVAILABILITYLOGSID    15 non-null     int64
 6   EVENTTIME               15 non-null     object
 7   ACTIVETIME              15 non-null     object
 8   PRIORITY                15 non-null     int64
 9   CONDITIONACTIVE         15 non-null     bool
 10  STATUS                  0 non-null      float64
 11  COMMENTS                0 non-null      float64
 12  Route                   0 non-null      float64
 13  Location                0 non-null      float64
 14  CHARGEABLE              15 non-null     int64
 15  BTAVAILABILITYALARMSID  15 non-null     int64
 16  GRACEPERIOD             15 non-null     int64
 17  GRACEPERIODUNIT         15 non-null     object
dtypes: bool(1), float64(4), int64(6), object(7)
memory usage: 2.1+ KB

In [5]:
# indexation a partir de 1 jusqu'à la longueur de notre dataframe
df.index = np.arange(1, len(df) + 1)

In [6]:
# On ajoute la colonne "Alarme_ number" à notre data frame 

df['Alarm_number'] ="Alarm "+ df.index.astype(str)  
print(df['Alarm_number'])

1      Alarm 1
2      Alarm 2
3      Alarm 3
4      Alarm 4
5      Alarm 5
6      Alarm 6
7      Alarm 7
8      Alarm 8
9      Alarm 9
10    Alarm 10
11    Alarm 11
12    Alarm 12
13    Alarm 13
14    Alarm 14
15    Alarm 15
Name: Alarm_number, dtype: object

In [7]:
#L= []
#for i in range(1,len(df)+1):
        #resultat = i 
       # print(resultat)
        #L.append(resultat)

### changement du format des colonnes eventime et activetime

In [8]:
# On remarque que nos données ne sont pas de type DateTime
## Convertir en données temporelles 

df[['EVENTTIME','ACTIVETIME']] = df[['EVENTTIME','ACTIVETIME']].apply(pd.to_datetime, format='%Y-%m-%dT%H:%M:%S%z')      # ou bien : '%Y-%m-%d %H:%M:%S%z'

In [9]:
print(df.info()," Les colonnes eventime et activetime sont au format datetime souhaité")

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15 entries, 1 to 15
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CALCULATIONTYPE         15 non-null     object
 1   MESSAGE                 15 non-null     object
 2   ALARMTYPE               15 non-null     object
 3   SERVERNODE              15 non-null     object
 4   ACKCOMMENT              15 non-null     int64
 5   BTAVAILABILITYLOGSID    15 non-null     int64
 6   EVENTTIME               15 non-null     datetime64[ns, UTC]
 7   ACTIVETIME              15 non-null     datetime64[ns, UTC]
 8   PRIORITY                15 non-null     int64
 9   CONDITIONACTIVE         15 non-null     bool
 10  STATUS                  0 non-null      float64
 11  COMMENTS                0 non-null      float64
 12  Route                   0 non-null      float64
 13  Location                0 non-null      float64
 14  CHARGEABLE              15 non-null     int64
 15  BTAVAILABILITYALARMSID  15 non-null     int64
 16  GRACEPERIOD             15 non-null     int64
 17  GRACEPERIODUNIT         15 non-null     object
 18  Alarm_number            15 non-null     object
dtypes: bool(1), datetime64[ns, UTC](2), float64(4), int64(6), object(6)
memory usage: 2.2+ KB
None  Les colonnes eventime et activetime sont au format datetime souhaité

## Data processing pour notre algo :

In [10]:
df.columns

Index(['CALCULATIONTYPE', 'MESSAGE', 'ALARMTYPE', 'SERVERNODE', 'ACKCOMMENT',
       'BTAVAILABILITYLOGSID', 'EVENTTIME', 'ACTIVETIME', 'PRIORITY',
       'CONDITIONACTIVE', 'STATUS', 'COMMENTS', 'Route', 'Location',
       'CHARGEABLE', 'BTAVAILABILITYALARMSID', 'GRACEPERIOD',
       'GRACEPERIODUNIT', 'Alarm_number'],
      dtype='object')

In [11]:
df['BTAVAILABILITYLOGSID'].value_counts()

2060070    1
2060069    1
2060076    1
2059912    1
2058722    1
2058899    1
2058641    1
2053623    1
2053629    1
2057424    1
2057503    1
2056902    1
2056901    1
2056759    1
2054139    1
Name: BTAVAILABILITYLOGSID, dtype: int64

In [12]:
data_algo  = df[['BTAVAILABILITYLOGSID','MESSAGE','ACTIVETIME','EVENTTIME','Alarm_number']]
data_algo.rename(columns = {'EVENTTIME':'TEND','ACTIVETIME':'TSTART'}, inplace = True)
data_algo = data_algo
data_algo

C:\Users\a888935\AppData\Local\Temp\ipykernel_11668\2693638450.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_algo.rename(columns = {'EVENTTIME':'TEND','ACTIVETIME':'TSTART'}, inplace = True)

,BTAVAILABILITYLOGSID,MESSAGE,TSTART,TEND,Alarm_number
1,2060070,Battery Charger Failure Cleared,2021-05-06 01:12:12+00:00,2021-05-06 01:18:16+00:00,Alarm 1
2,2060069,LVPS Line Failure Cleared,2021-05-06 01:12:12+00:00,2021-05-06 01:18:16+00:00,Alarm 2
3,2060076,LVPS Line Failure Cleared,2021-05-06 01:12:16+00:00,2021-05-06 01:18:12+00:00,Alarm 3
4,2059912,Train in Full Manual Mode Cleared,2021-05-06 01:13:18+00:00,2021-05-06 01:21:23+00:00,Alarm 4
5,2058722,Emergency Brake Trainline Deenergized VATC Cle...,2021-05-06 01:15:28+00:00,2021-05-06 01:46:12+00:00,Alarm 5
6,2058899,Inaccurate Station Stop Short Cleared,2021-05-06 01:27:25+00:00,2021-05-06 01:43:05+00:00,Alarm 6
7,2058641,Train Failed to Arrive Cleared,2021-05-06 01:41:38+00:00,2021-05-06 01:47:35+00:00,Alarm 7
8,2053623,Emergency Brake Trainline Deenergized VATC Cle...,2021-05-06 01:48:51+00:00,2021-05-06 04:59:58+00:00,Alarm 8
9,2053629,Inaccurate Station Stop Short Cleared,2021-05-06 01:58:25+00:00,2021-05-06 04:59:54+00:00,Alarm 9
10,2057424,Train Failed to Arrive Cleared,2021-05-06 02:22:27+00:00,2021-05-06 02:26:56+00:00,Alarm 10
11,2057503,Unscheduled Stop Cleared,2021-05-06 02:22:48+00:00,2021-05-06 02:23:34+00:00,Alarm 11
12,2056902,Battery Charger Failure Cleared,2021-05-06 02:47:22+00:00,2021-05-06 02:51:47+00:00,Alarm 12
13,2056901,LVPS Line Failure Cleared,2021-05-06 02:47:22+00:00,2021-05-06 02:51:47+00:00,Alarm 13
14,2056759,Summary Doors Failed to Close Cleared,2021-05-06 02:49:33+00:00,2021-05-06 02:55:31+00:00,Alarm 14
15,2054139,Unscheduled Stop Cleared,2021-05-06 04:38:07+00:00,2021-05-06 04:38:25+00:00,Alarm 15

In [13]:
data_algo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15 entries, 1 to 15
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   BTAVAILABILITYLOGSID  15 non-null     int64
 1   MESSAGE               15 non-null     object
 2   TSTART                15 non-null     datetime64[ns, UTC]
 3   TEND                  15 non-null     datetime64[ns, UTC]
 4   Alarm_number          15 non-null     object
dtypes: datetime64[ns, UTC](2), int64(1), object(2)
memory usage: 720.0+ bytes

In [14]:
### Creation de la colonne delta time qui correspond a la durée des alarmes : 

data_algo["delta_time"] = (data_algo["TEND"] - pd.to_timedelta(data_algo["TSTART"].dt.time.astype(str))) - data_algo["TEND"].dt.floor("d")
data_algo["delta_time"]

C:\Users\a888935\AppData\Local\Temp\ipykernel_11668\2118922577.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_algo["delta_time"] = (data_algo["TEND"] - pd.to_timedelta(data_algo["TSTART"].dt.time.astype(str))) - data_algo["TEND"].dt.floor("d")

1    0 days 00:06:04
2    0 days 00:06:04
3    0 days 00:05:56
4    0 days 00:08:05
5    0 days 00:30:44
6    0 days 00:15:40
7    0 days 00:05:57
8    0 days 03:11:07
9    0 days 03:01:29
10   0 days 00:04:29
11   0 days 00:00:46
12   0 days 00:04:25
13   0 days 00:04:25
14   0 days 00:05:58
15   0 days 00:00:18
Name: delta_time, dtype: timedelta64[ns]

In [15]:
data_algo.info

<bound method DataFrame.info of     BTAVAILABILITYLOGSID                                            MESSAGE  \
1                2060070                    Battery Charger Failure Cleared
2                2060069                          LVPS Line Failure Cleared
3                2060076                          LVPS Line Failure Cleared
4                2059912                  Train in Full Manual Mode Cleared
5                2058722  Emergency Brake Trainline Deenergized VATC Cle...
6                2058899              Inaccurate Station Stop Short Cleared
7                2058641                     Train Failed to Arrive Cleared
8                2053623  Emergency Brake Trainline Deenergized VATC Cle...
9                2053629              Inaccurate Station Stop Short Cleared
10               2057424                     Train Failed to Arrive Cleared
11               2057503                           Unscheduled Stop Cleared
12               2056902                    Battery Charger Failure Cleared
13               2056901                          LVPS Line Failure Cleared
14               2056759              Summary Doors Failed to Close Cleared
15               2054139                           Unscheduled Stop Cleared

                      TSTART                      TEND Alarm_number  \
1  2021-05-06 01:12:12+00:00 2021-05-06 01:18:16+00:00      Alarm 1
2  2021-05-06 01:12:12+00:00 2021-05-06 01:18:16+00:00      Alarm 2
3  2021-05-06 01:12:16+00:00 2021-05-06 01:18:12+00:00      Alarm 3
4  2021-05-06 01:13:18+00:00 2021-05-06 01:21:23+00:00      Alarm 4
5  2021-05-06 01:15:28+00:00 2021-05-06 01:46:12+00:00      Alarm 5
6  2021-05-06 01:27:25+00:00 2021-05-06 01:43:05+00:00      Alarm 6
7  2021-05-06 01:41:38+00:00 2021-05-06 01:47:35+00:00      Alarm 7
8  2021-05-06 01:48:51+00:00 2021-05-06 04:59:58+00:00      Alarm 8
9  2021-05-06 01:58:25+00:00 2021-05-06 04:59:54+00:00      Alarm 9
10 2021-05-06 02:22:27+00:00 2021-05-06 02:26:56+00:00     Alarm 10
11 2021-05-06 02:22:48+00:00 2021-05-06 02:23:34+00:00     Alarm 11
12 2021-05-06 02:47:22+00:00 2021-05-06 02:51:47+00:00     Alarm 12
13 2021-05-06 02:47:22+00:00 2021-05-06 02:51:47+00:00     Alarm 13
14 2021-05-06 02:49:33+00:00 2021-05-06 02:55:31+00:00     Alarm 14
15 2021-05-06 04:38:07+00:00 2021-05-06 04:38:25+00:00     Alarm 15

        delta_time
1  0 days 00:06:04
2  0 days 00:06:04
3  0 days 00:05:56
4  0 days 00:08:05
5  0 days 00:30:44
6  0 days 00:15:40
7  0 days 00:05:57
8  0 days 03:11:07
9  0 days 03:01:29
10 0 days 00:04:29
11 0 days 00:00:46
12 0 days 00:04:25
13 0 days 00:04:25
14 0 days 00:05:58
15 0 days 00:00:18  >

In [16]:
data_algo

,BTAVAILABILITYLOGSID,MESSAGE,TSTART,TEND,Alarm_number,delta_time
1,2060070,Battery Charger Failure Cleared,2021-05-06 01:12:12+00:00,2021-05-06 01:18:16+00:00,Alarm 1,0 days 00:06:04
2,2060069,LVPS Line Failure Cleared,2021-05-06 01:12:12+00:00,2021-05-06 01:18:16+00:00,Alarm 2,0 days 00:06:04
3,2060076,LVPS Line Failure Cleared,2021-05-06 01:12:16+00:00,2021-05-06 01:18:12+00:00,Alarm 3,0 days 00:05:56
4,2059912,Train in Full Manual Mode Cleared,2021-05-06 01:13:18+00:00,2021-05-06 01:21:23+00:00,Alarm 4,0 days 00:08:05
5,2058722,Emergency Brake Trainline Deenergized VATC Cle...,2021-05-06 01:15:28+00:00,2021-05-06 01:46:12+00:00,Alarm 5,0 days 00:30:44
6,2058899,Inaccurate Station Stop Short Cleared,2021-05-06 01:27:25+00:00,2021-05-06 01:43:05+00:00,Alarm 6,0 days 00:15:40
7,2058641,Train Failed to Arrive Cleared,2021-05-06 01:41:38+00:00,2021-05-06 01:47:35+00:00,Alarm 7,0 days 00:05:57
8,2053623,Emergency Brake Trainline Deenergized VATC Cle...,2021-05-06 01:48:51+00:00,2021-05-06 04:59:58+00:00,Alarm 8,0 days 03:11:07
9,2053629,Inaccurate Station Stop Short Cleared,2021-05-06 01:58:25+00:00,2021-05-06 04:59:54+00:00,Alarm 9,0 days 03:01:29
10,2057424,Train Failed to Arrive Cleared,2021-05-06 02:22:27+00:00,2021-05-06 02:26:56+00:00,Alarm 10,0 days 00:04:29
11,2057503,Unscheduled Stop Cleared,2021-05-06 02:22:48+00:00,2021-05-06 02:23:34+00:00,Alarm 11,0 days 00:00:46
12,2056902,Battery Charger Failure Cleared,2021-05-06 02:47:22+00:00,2021-05-06 02:51:47+00:00,Alarm 12,0 days 00:04:25
13,2056901,LVPS Line Failure Cleared,2021-05-06 02:47:22+00:00,2021-05-06 02:51:47+00:00,Alarm 13,0 days 00:04:25
14,2056759,Summary Doors Failed to Close Cleared,2021-05-06 02:49:33+00:00,2021-05-06 02:55:31+00:00,Alarm 14,0 days 00:05:58
15,2054139,Unscheduled Stop Cleared,2021-05-06 04:38:07+00:00,2021-05-06 04:38:25+00:00,Alarm 15,0 days 00:00:18

In [17]:
# trier data frame selon TSTART  : 

# Sort DataFrame by date column
#data_algo.sort_values(by='T0', inplace = True)
#data_algo

In [18]:
data_algo[['TSTART','TEND','Alarm_number']].values

array([[Timestamp('2021-05-06 01:12:12+0000', tz='UTC'),
        Timestamp('2021-05-06 01:18:16+0000', tz='UTC'), 'Alarm 1'],
       [Timestamp('2021-05-06 01:12:12+0000', tz='UTC'),
        Timestamp('2021-05-06 01:18:16+0000', tz='UTC'), 'Alarm 2'],
       [Timestamp('2021-05-06 01:12:16+0000', tz='UTC'),
        Timestamp('2021-05-06 01:18:12+0000', tz='UTC'), 'Alarm 3'],
       [Timestamp('2021-05-06 01:13:18+0000', tz='UTC'),
        Timestamp('2021-05-06 01:21:23+0000', tz='UTC'), 'Alarm 4'],
       [Timestamp('2021-05-06 01:15:28+0000', tz='UTC'),
        Timestamp('2021-05-06 01:46:12+0000', tz='UTC'), 'Alarm 5'],
       [Timestamp('2021-05-06 01:27:25+0000', tz='UTC'),
        Timestamp('2021-05-06 01:43:05+0000', tz='UTC'), 'Alarm 6'],
       [Timestamp('2021-05-06 01:41:38+0000', tz='UTC'),
        Timestamp('2021-05-06 01:47:35+0000', tz='UTC'), 'Alarm 7'],
       [Timestamp('2021-05-06 01:48:51+0000', tz='UTC'),
        Timestamp('2021-05-06 04:59:58+0000', tz='UTC'), 'Alarm 8'],
       [Timestamp('2021-05-06 01:58:25+0000', tz='UTC'),
        Timestamp('2021-05-06 04:59:54+0000', tz='UTC'), 'Alarm 9'],
       [Timestamp('2021-05-06 02:22:27+0000', tz='UTC'),
        Timestamp('2021-05-06 02:26:56+0000', tz='UTC'), 'Alarm 10'],
       [Timestamp('2021-05-06 02:22:48+0000', tz='UTC'),
        Timestamp('2021-05-06 02:23:34+0000', tz='UTC'), 'Alarm 11'],
       [Timestamp('2021-05-06 02:47:22+0000', tz='UTC'),
        Timestamp('2021-05-06 02:51:47+0000', tz='UTC'), 'Alarm 12'],
       [Timestamp('2021-05-06 02:47:22+0000', tz='UTC'),
        Timestamp('2021-05-06 02:51:47+0000', tz='UTC'), 'Alarm 13'],
       [Timestamp('2021-05-06 02:49:33+0000', tz='UTC'),
        Timestamp('2021-05-06 02:55:31+0000', tz='UTC'), 'Alarm 14'],
       [Timestamp('2021-05-06 04:38:07+0000', tz='UTC'),
        Timestamp('2021-05-06 04:38:25+0000', tz='UTC'), 'Alarm 15']],
      dtype=object)

In [19]:
slices = []

def add_slices(row):
    
    slices.append({'slice_name' : row['Alarm_number'] +'_START','Time' :row['TSTART'],'duration' : row['delta_time']})
    slices.append({'slice_name' : row['Alarm_number'] +'_END','Time' :row['TEND'],'duration' : row['delta_time']})
   

    
data_algo.apply(add_slices,axis = 1)

slices

[{'slice_name': 'Alarm 1_START',
  'Time': Timestamp('2021-05-06 01:12:12+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:06:04')},
 {'slice_name': 'Alarm 1_END',
  'Time': Timestamp('2021-05-06 01:18:16+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:06:04')},
 {'slice_name': 'Alarm 2_START',
  'Time': Timestamp('2021-05-06 01:12:12+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:06:04')},
 {'slice_name': 'Alarm 2_END',
  'Time': Timestamp('2021-05-06 01:18:16+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:06:04')},
 {'slice_name': 'Alarm 3_START',
  'Time': Timestamp('2021-05-06 01:12:16+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:05:56')},
 {'slice_name': 'Alarm 3_END',
  'Time': Timestamp('2021-05-06 01:18:12+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:05:56')},
 {'slice_name': 'Alarm 4_START',
  'Time': Timestamp('2021-05-06 01:13:18+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:08:05')},
 {'slice_name': 'Alarm 4_END',
  'Time': Timestamp('2021-05-06 01:21:23+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:08:05')},
 {'slice_name': 'Alarm 5_START',
  'Time': Timestamp('2021-05-06 01:15:28+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:30:44')},
 {'slice_name': 'Alarm 5_END',
  'Time': Timestamp('2021-05-06 01:46:12+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:30:44')},
 {'slice_name': 'Alarm 6_START',
  'Time': Timestamp('2021-05-06 01:27:25+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:15:40')},
 {'slice_name': 'Alarm 6_END',
  'Time': Timestamp('2021-05-06 01:43:05+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:15:40')},
 {'slice_name': 'Alarm 7_START',
  'Time': Timestamp('2021-05-06 01:41:38+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:05:57')},
 {'slice_name': 'Alarm 7_END',
  'Time': Timestamp('2021-05-06 01:47:35+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:05:57')},
 {'slice_name': 'Alarm 8_START',
  'Time': Timestamp('2021-05-06 01:48:51+0000', tz='UTC'),
  'duration': Timedelta('0 days 03:11:07')},
 {'slice_name': 'Alarm 8_END',
  'Time': Timestamp('2021-05-06 04:59:58+0000', tz='UTC'),
  'duration': Timedelta('0 days 03:11:07')},
 {'slice_name': 'Alarm 9_START',
  'Time': Timestamp('2021-05-06 01:58:25+0000', tz='UTC'),
  'duration': Timedelta('0 days 03:01:29')},
 {'slice_name': 'Alarm 9_END',
  'Time': Timestamp('2021-05-06 04:59:54+0000', tz='UTC'),
  'duration': Timedelta('0 days 03:01:29')},
 {'slice_name': 'Alarm 10_START',
  'Time': Timestamp('2021-05-06 02:22:27+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:04:29')},
 {'slice_name': 'Alarm 10_END',
  'Time': Timestamp('2021-05-06 02:26:56+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:04:29')},
 {'slice_name': 'Alarm 11_START',
  'Time': Timestamp('2021-05-06 02:22:48+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:00:46')},
 {'slice_name': 'Alarm 11_END',
  'Time': Timestamp('2021-05-06 02:23:34+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:00:46')},
 {'slice_name': 'Alarm 12_START',
  'Time': Timestamp('2021-05-06 02:47:22+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:04:25')},
 {'slice_name': 'Alarm 12_END',
  'Time': Timestamp('2021-05-06 02:51:47+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:04:25')},
 {'slice_name': 'Alarm 13_START',
  'Time': Timestamp('2021-05-06 02:47:22+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:04:25')},
 {'slice_name': 'Alarm 13_END',
  'Time': Timestamp('2021-05-06 02:51:47+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:04:25')},
 {'slice_name': 'Alarm 14_START',
  'Time': Timestamp('2021-05-06 02:49:33+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:05:58')},
 {'slice_name': 'Alarm 14_END',
  'Time': Timestamp('2021-05-06 02:55:31+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:05:58')},
 {'slice_name': 'Alarm 15_START',
  'Time': Timestamp('2021-05-06 04:38:07+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:00:18')},
 {'slice_name': 'Alarm 15_END',
  'Time': Timestamp('2021-05-06 04:38:25+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:00:18')}]

In [23]:
Slices_sorted = sorted(slices, key=lambda el: el['Time'])
Slices_sorted

[{'slice_name': 'Alarm 1_START',
  'Time': Timestamp('2021-05-06 01:12:12+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:06:04')},
 {'slice_name': 'Alarm 2_START',
  'Time': Timestamp('2021-05-06 01:12:12+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:06:04')},
 {'slice_name': 'Alarm 3_START',
  'Time': Timestamp('2021-05-06 01:12:16+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:05:56')},
 {'slice_name': 'Alarm 4_START',
  'Time': Timestamp('2021-05-06 01:13:18+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:08:05')},
 {'slice_name': 'Alarm 5_START',
  'Time': Timestamp('2021-05-06 01:15:28+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:30:44')},
 {'slice_name': 'Alarm 3_END',
  'Time': Timestamp('2021-05-06 01:18:12+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:05:56')},
 {'slice_name': 'Alarm 1_END',
  'Time': Timestamp('2021-05-06 01:18:16+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:06:04')},
 {'slice_name': 'Alarm 2_END',
  'Time': Timestamp('2021-05-06 01:18:16+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:06:04')},
 {'slice_name': 'Alarm 4_END',
  'Time': Timestamp('2021-05-06 01:21:23+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:08:05')},
 {'slice_name': 'Alarm 6_START',
  'Time': Timestamp('2021-05-06 01:27:25+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:15:40')},
 {'slice_name': 'Alarm 7_START',
  'Time': Timestamp('2021-05-06 01:41:38+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:05:57')},
 {'slice_name': 'Alarm 6_END',
  'Time': Timestamp('2021-05-06 01:43:05+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:15:40')},
 {'slice_name': 'Alarm 5_END',
  'Time': Timestamp('2021-05-06 01:46:12+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:30:44')},
 {'slice_name': 'Alarm 7_END',
  'Time': Timestamp('2021-05-06 01:47:35+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:05:57')},
 {'slice_name': 'Alarm 8_START',
  'Time': Timestamp('2021-05-06 01:48:51+0000', tz='UTC'),
  'duration': Timedelta('0 days 03:11:07')},
 {'slice_name': 'Alarm 9_START',
  'Time': Timestamp('2021-05-06 01:58:25+0000', tz='UTC'),
  'duration': Timedelta('0 days 03:01:29')},
 {'slice_name': 'Alarm 10_START',
  'Time': Timestamp('2021-05-06 02:22:27+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:04:29')},
 {'slice_name': 'Alarm 11_START',
  'Time': Timestamp('2021-05-06 02:22:48+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:00:46')},
 {'slice_name': 'Alarm 11_END',
  'Time': Timestamp('2021-05-06 02:23:34+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:00:46')},
 {'slice_name': 'Alarm 10_END',
  'Time': Timestamp('2021-05-06 02:26:56+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:04:29')},
 {'slice_name': 'Alarm 12_START',
  'Time': Timestamp('2021-05-06 02:47:22+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:04:25')},
 {'slice_name': 'Alarm 13_START',
  'Time': Timestamp('2021-05-06 02:47:22+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:04:25')},
 {'slice_name': 'Alarm 14_START',
  'Time': Timestamp('2021-05-06 02:49:33+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:05:58')},
 {'slice_name': 'Alarm 12_END',
  'Time': Timestamp('2021-05-06 02:51:47+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:04:25')},
 {'slice_name': 'Alarm 13_END',
  'Time': Timestamp('2021-05-06 02:51:47+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:04:25')},
 {'slice_name': 'Alarm 14_END',
  'Time': Timestamp('2021-05-06 02:55:31+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:05:58')},
 {'slice_name': 'Alarm 15_START',
  'Time': Timestamp('2021-05-06 04:38:07+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:00:18')},
 {'slice_name': 'Alarm 15_END',
  'Time': Timestamp('2021-05-06 04:38:25+0000', tz='UTC'),
  'duration': Timedelta('0 days 00:00:18')},
 {'slice_name': 'Alarm 9_END',
  'Time': Timestamp('2021-05-06 04:59:54+0000', tz='UTC'),
  'duration': Timedelta('0 days 03:01:29')},
 {'slice_name': 'Alarm 8_END',
  'Time': Timestamp('2021-05-06 04:59:58+0000', tz='UTC'),
  'duration': Timedelta('0 days 03:11:07')}]

In [240]:
s = pd.DataFrame.from_dict(Slices_sorted)
s.index = np.arange(1, len(s) + 1)

In [ ]:
s1: 1.12.12 --> 1.12.16

In [313]:
data_algo["TSTART"][1]

Timestamp('2021-05-06 01:12:12+0000', tz='UTC')

In [ ]:
s1_start = data_algo['TSTART'].min()
s2_start = s1_start+ data["Slice_duration"][1]

In [320]:
temp =[s1_start]
#temp.append(s1_start)
for i in range (1,len(data)):
    si = s1_start+ data["Slice_duration"][i]
    #temp.append("S"+ str(i) +"Start"+ ":" +str(si))
    temp.append(si)
    
temp

[Timestamp('2021-05-06 01:12:12+0000', tz='UTC'),
 Timestamp('2021-05-06 01:12:16+0000', tz='UTC'),
 Timestamp('2021-05-06 01:13:14+0000', tz='UTC'),
 Timestamp('2021-05-06 01:14:22+0000', tz='UTC'),
 Timestamp('2021-05-06 01:14:56+0000', tz='UTC'),
 Timestamp('2021-05-06 01:12:16+0000', tz='UTC'),
 Timestamp('2021-05-06 01:15:19+0000', tz='UTC'),
 Timestamp('2021-05-06 01:18:14+0000', tz='UTC'),
 Timestamp('2021-05-06 01:26:25+0000', tz='UTC'),
 Timestamp('2021-05-06 01:13:39+0000', tz='UTC'),
 Timestamp('2021-05-06 01:15:19+0000', tz='UTC'),
 Timestamp('2021-05-06 01:13:35+0000', tz='UTC'),
 Timestamp('2021-05-06 01:13:28+0000', tz='UTC'),
 Timestamp('2021-05-06 01:21:46+0000', tz='UTC'),
 Timestamp('2021-05-06 01:36:14+0000', tz='UTC'),
 Timestamp('2021-05-06 01:12:33+0000', tz='UTC'),
 Timestamp('2021-05-06 01:12:58+0000', tz='UTC'),
 Timestamp('2021-05-06 01:15:34+0000', tz='UTC'),
 Timestamp('2021-05-06 01:32:38+0000', tz='UTC'),
 Timestamp('2021-05-06 01:14:23+0000', tz='UTC'),
 Timestamp('2021-05-06 01:14:26+0000', tz='UTC'),
 Timestamp('2021-05-06 01:15:56+0000', tz='UTC'),
 Timestamp('2021-05-06 02:54:48+0000', tz='UTC'),
 Timestamp('2021-05-06 01:12:30+0000', tz='UTC'),
 Timestamp('2021-05-06 01:33:41+0000', tz='UTC')]

In [343]:
a = pd.DataFrame({"Slices" : temp})
a.index = np.arange(1, len(a) + 1)
#a["slice_end"] =

In [330]:
print("i"+str(i))
print(f"i : {i}")

i2021-05-06 01:33:41+00:00
i : 2021-05-06 01:33:41+00:00

In [344]:
data_algo.t

,BTAVAILABILITYLOGSID,MESSAGE,TSTART,TEND,Alarm_number,delta_time
1,2060070,Battery Charger Failure Cleared,2021-05-06 01:12:12+00:00,2021-05-06 01:18:16+00:00,Alarm 1,0 days 00:06:04
2,2060069,LVPS Line Failure Cleared,2021-05-06 01:12:12+00:00,2021-05-06 01:18:16+00:00,Alarm 2,0 days 00:06:04
3,2060076,LVPS Line Failure Cleared,2021-05-06 01:12:16+00:00,2021-05-06 01:18:12+00:00,Alarm 3,0 days 00:05:56
4,2059912,Train in Full Manual Mode Cleared,2021-05-06 01:13:18+00:00,2021-05-06 01:21:23+00:00,Alarm 4,0 days 00:08:05
5,2058722,Emergency Brake Trainline Deenergized VATC Cle...,2021-05-06 01:15:28+00:00,2021-05-06 01:46:12+00:00,Alarm 5,0 days 00:30:44
6,2058899,Inaccurate Station Stop Short Cleared,2021-05-06 01:27:25+00:00,2021-05-06 01:43:05+00:00,Alarm 6,0 days 00:15:40
7,2058641,Train Failed to Arrive Cleared,2021-05-06 01:41:38+00:00,2021-05-06 01:47:35+00:00,Alarm 7,0 days 00:05:57
8,2053623,Emergency Brake Trainline Deenergized VATC Cle...,2021-05-06 01:48:51+00:00,2021-05-06 04:59:58+00:00,Alarm 8,0 days 03:11:07
9,2053629,Inaccurate Station Stop Short Cleared,2021-05-06 01:58:25+00:00,2021-05-06 04:59:54+00:00,Alarm 9,0 days 03:01:29
10,2057424,Train Failed to Arrive Cleared,2021-05-06 02:22:27+00:00,2021-05-06 02:26:56+00:00,Alarm 10,0 days 00:04:29
11,2057503,Unscheduled Stop Cleared,2021-05-06 02:22:48+00:00,2021-05-06 02:23:34+00:00,Alarm 11,0 days 00:00:46
12,2056902,Battery Charger Failure Cleared,2021-05-06 02:47:22+00:00,2021-05-06 02:51:47+00:00,Alarm 12,0 days 00:04:25
13,2056901,LVPS Line Failure Cleared,2021-05-06 02:47:22+00:00,2021-05-06 02:51:47+00:00,Alarm 13,0 days 00:04:25
14,2056759,Summary Doors Failed to Close Cleared,2021-05-06 02:49:33+00:00,2021-05-06 02:55:31+00:00,Alarm 14,0 days 00:05:58
15,2054139,Unscheduled Stop Cleared,2021-05-06 04:38:07+00:00,2021-05-06 04:38:25+00:00,Alarm 15,0 days 00:00:18

In [335]:
temp2 = []
for i in a['Slices']:
    print(f'i : {i}')
    for j in data_algo["TSTART"]:
        print(f'j : {j}')
        if (data_algo["TSTART"][j]<= a['Slices'][i+1]) and (data_algo["TSTART"][j]<= a['Slices'][i]):
        #if (j<= i+1) and (j>=i):
            print(data_algo[j])
    print()

i : 2021-05-06 01:12:12+00:00
j : 2021-05-06 01:12:12+00:00

KeyError: Timestamp('2021-05-06 01:12:12+0000', tz='UTC')

In [338]:
i>j

False

In [340]:
i

Timestamp('2021-05-06 01:12:12+0000', tz='UTC')

In [304]:
data.head()

  Slices  Slice_duration
1    S 1 0 days 00:00:04
2    S 2 0 days 00:01:02
3    S 3 0 days 00:02:10
4    S 4 0 days 00:02:44
5    S 5 0 days 00:00:04

In [305]:
s.head()

      slice_name                      Time        duration
1  Alarm 1_START 2021-05-06 01:12:12+00:00 0 days 00:06:04
2  Alarm 2_START 2021-05-06 01:12:12+00:00 0 days 00:06:04
3  Alarm 3_START 2021-05-06 01:12:16+00:00 0 days 00:05:56
4  Alarm 4_START 2021-05-06 01:13:18+00:00 0 days 00:08:05
5  Alarm 5_START 2021-05-06 01:15:28+00:00 0 days 00:30:44

In [241]:
s

        slice_name                      Time        duration
1    Alarm 1_START 2021-05-06 01:12:12+00:00 0 days 00:06:04
2    Alarm 2_START 2021-05-06 01:12:12+00:00 0 days 00:06:04
3    Alarm 3_START 2021-05-06 01:12:16+00:00 0 days 00:05:56
4    Alarm 4_START 2021-05-06 01:13:18+00:00 0 days 00:08:05
5    Alarm 5_START 2021-05-06 01:15:28+00:00 0 days 00:30:44
6      Alarm 3_END 2021-05-06 01:18:12+00:00 0 days 00:05:56
7      Alarm 1_END 2021-05-06 01:18:16+00:00 0 days 00:06:04
8      Alarm 2_END 2021-05-06 01:18:16+00:00 0 days 00:06:04
9      Alarm 4_END 2021-05-06 01:21:23+00:00 0 days 00:08:05
10   Alarm 6_START 2021-05-06 01:27:25+00:00 0 days 00:15:40
11   Alarm 7_START 2021-05-06 01:41:38+00:00 0 days 00:05:57
12     Alarm 6_END 2021-05-06 01:43:05+00:00 0 days 00:15:40
13     Alarm 5_END 2021-05-06 01:46:12+00:00 0 days 00:30:44
14     Alarm 7_END 2021-05-06 01:47:35+00:00 0 days 00:05:57
15   Alarm 8_START 2021-05-06 01:48:51+00:00 0 days 03:11:07
16   Alarm 9_START 2021-05-06 01:58:25+00:00 0 days 03:01:29
17  Alarm 10_START 2021-05-06 02:22:27+00:00 0 days 00:04:29
18  Alarm 11_START 2021-05-06 02:22:48+00:00 0 days 00:00:46
19    Alarm 11_END 2021-05-06 02:23:34+00:00 0 days 00:00:46
20    Alarm 10_END 2021-05-06 02:26:56+00:00 0 days 00:04:29
21  Alarm 12_START 2021-05-06 02:47:22+00:00 0 days 00:04:25
22  Alarm 13_START 2021-05-06 02:47:22+00:00 0 days 00:04:25
23  Alarm 14_START 2021-05-06 02:49:33+00:00 0 days 00:05:58
24    Alarm 12_END 2021-05-06 02:51:47+00:00 0 days 00:04:25
25    Alarm 13_END 2021-05-06 02:51:47+00:00 0 days 00:04:25
26    Alarm 14_END 2021-05-06 02:55:31+00:00 0 days 00:05:58
27  Alarm 15_START 2021-05-06 04:38:07+00:00 0 days 00:00:18
28    Alarm 15_END 2021-05-06 04:38:25+00:00 0 days 00:00:18
29     Alarm 9_END 2021-05-06 04:59:54+00:00 0 days 03:01:29
30     Alarm 8_END 2021-05-06 04:59:58+00:00 0 days 03:11:07

In [ ]:
# on va essayer d'enlever les

In [25]:
print(s["Time"].unique())
s_unique = s["Time"].unique()
#print(type(s["Subjects"].unique()))

<DatetimeArray>
['2021-05-06 01:12:12+00:00', '2021-05-06 01:12:16+00:00',
 '2021-05-06 01:13:18+00:00', '2021-05-06 01:15:28+00:00',
 '2021-05-06 01:18:12+00:00', '2021-05-06 01:18:16+00:00',
 '2021-05-06 01:21:23+00:00', '2021-05-06 01:27:25+00:00',
 '2021-05-06 01:41:38+00:00', '2021-05-06 01:43:05+00:00',
 '2021-05-06 01:46:12+00:00', '2021-05-06 01:47:35+00:00',
 '2021-05-06 01:48:51+00:00', '2021-05-06 01:58:25+00:00',
 '2021-05-06 02:22:27+00:00', '2021-05-06 02:22:48+00:00',
 '2021-05-06 02:23:34+00:00', '2021-05-06 02:26:56+00:00',
 '2021-05-06 02:47:22+00:00', '2021-05-06 02:49:33+00:00',
 '2021-05-06 02:51:47+00:00', '2021-05-06 02:55:31+00:00',
 '2021-05-06 04:38:07+00:00', '2021-05-06 04:38:25+00:00',
 '2021-05-06 04:59:54+00:00', '2021-05-06 04:59:58+00:00']
Length: 26, dtype: datetime64[ns, UTC]

In [26]:
len(s_unique)

26

In [71]:
t= []
u = []
for i in range(1,len(s_unique)):
    t.append(s_unique[i]- s_unique[i-1]) 
    if s_unique[i] != s_unique[i-1]: 
        u.append("S " + str(i))

In [72]:
t

[Timedelta('0 days 00:00:04'),
 Timedelta('0 days 00:01:02'),
 Timedelta('0 days 00:02:10'),
 Timedelta('0 days 00:02:44'),
 Timedelta('0 days 00:00:04'),
 Timedelta('0 days 00:03:07'),
 Timedelta('0 days 00:06:02'),
 Timedelta('0 days 00:14:13'),
 Timedelta('0 days 00:01:27'),
 Timedelta('0 days 00:03:07'),
 Timedelta('0 days 00:01:23'),
 Timedelta('0 days 00:01:16'),
 Timedelta('0 days 00:09:34'),
 Timedelta('0 days 00:24:02'),
 Timedelta('0 days 00:00:21'),
 Timedelta('0 days 00:00:46'),
 Timedelta('0 days 00:03:22'),
 Timedelta('0 days 00:20:26'),
 Timedelta('0 days 00:02:11'),
 Timedelta('0 days 00:02:14'),
 Timedelta('0 days 00:03:44'),
 Timedelta('0 days 01:42:36'),
 Timedelta('0 days 00:00:18'),
 Timedelta('0 days 00:21:29'),
 Timedelta('0 days 00:00:04')]

In [350]:
data.to_csv('data.csv')

In [74]:
u

['S 1',
 'S 2',
 'S 3',
 'S 4',
 'S 5',
 'S 6',
 'S 7',
 'S 8',
 'S 9',
 'S 10',
 'S 11',
 'S 12',
 'S 13',
 'S 14',
 'S 15',
 'S 16',
 'S 17',
 'S 18',
 'S 19',
 'S 20',
 'S 21',
 'S 22',
 'S 23',
 'S 24',
 'S 25']

In [238]:
data = pd.DataFrame({"Slices" : u,"Slice_duration": t})
data.index = np.arange(1, len(data) + 1)
data

   Slices  Slice_duration
1     S 1 0 days 00:00:04
2     S 2 0 days 00:01:02
3     S 3 0 days 00:02:10
4     S 4 0 days 00:02:44
5     S 5 0 days 00:00:04
6     S 6 0 days 00:03:07
7     S 7 0 days 00:06:02
8     S 8 0 days 00:14:13
9     S 9 0 days 00:01:27
10   S 10 0 days 00:03:07
11   S 11 0 days 00:01:23
12   S 12 0 days 00:01:16
13   S 13 0 days 00:09:34
14   S 14 0 days 00:24:02
15   S 15 0 days 00:00:21
16   S 16 0 days 00:00:46
17   S 17 0 days 00:03:22
18   S 18 0 days 00:20:26
19   S 19 0 days 00:02:11
20   S 20 0 days 00:02:14
21   S 21 0 days 00:03:44
22   S 22 0 days 01:42:36
23   S 23 0 days 00:00:18
24   S 24 0 days 00:21:29
25   S 25 0 days 00:00:04

In [345]:
np.sum(data["Slice_duration"])

Timedelta('0 days 03:47:46')

In [346]:
slice_cumul = np.cumsum(data["Slice_duration"])
slice_cumul

1    0 days 00:00:04
2    0 days 00:01:06
3    0 days 00:03:16
4    0 days 00:06:00
5    0 days 00:06:04
6    0 days 00:09:11
7    0 days 00:15:13
8    0 days 00:29:26
9    0 days 00:30:53
10   0 days 00:34:00
11   0 days 00:35:23
12   0 days 00:36:39
13   0 days 00:46:13
14   0 days 01:10:15
15   0 days 01:10:36
16   0 days 01:11:22
17   0 days 01:14:44
18   0 days 01:35:10
19   0 days 01:37:21
20   0 days 01:39:35
21   0 days 01:43:19
22   0 days 03:25:55
23   0 days 03:26:13
24   0 days 03:47:42
25   0 days 03:47:46
Name: Slice_duration, dtype: timedelta64[ns]

In [276]:
s

        slice_name                      Time        duration
1    Alarm 1_START 2021-05-06 01:12:12+00:00 0 days 00:06:04
2    Alarm 2_START 2021-05-06 01:12:12+00:00 0 days 00:06:04
3    Alarm 3_START 2021-05-06 01:12:16+00:00 0 days 00:05:56
4    Alarm 4_START 2021-05-06 01:13:18+00:00 0 days 00:08:05
5    Alarm 5_START 2021-05-06 01:15:28+00:00 0 days 00:30:44
6      Alarm 3_END 2021-05-06 01:18:12+00:00 0 days 00:05:56
7      Alarm 1_END 2021-05-06 01:18:16+00:00 0 days 00:06:04
8      Alarm 2_END 2021-05-06 01:18:16+00:00 0 days 00:06:04
9      Alarm 4_END 2021-05-06 01:21:23+00:00 0 days 00:08:05
10   Alarm 6_START 2021-05-06 01:27:25+00:00 0 days 00:15:40
11   Alarm 7_START 2021-05-06 01:41:38+00:00 0 days 00:05:57
12     Alarm 6_END 2021-05-06 01:43:05+00:00 0 days 00:15:40
13     Alarm 5_END 2021-05-06 01:46:12+00:00 0 days 00:30:44
14     Alarm 7_END 2021-05-06 01:47:35+00:00 0 days 00:05:57
15   Alarm 8_START 2021-05-06 01:48:51+00:00 0 days 03:11:07
16   Alarm 9_START 2021-05-06 01:58:25+00:00 0 days 03:01:29
17  Alarm 10_START 2021-05-06 02:22:27+00:00 0 days 00:04:29
18  Alarm 11_START 2021-05-06 02:22:48+00:00 0 days 00:00:46
19    Alarm 11_END 2021-05-06 02:23:34+00:00 0 days 00:00:46
20    Alarm 10_END 2021-05-06 02:26:56+00:00 0 days 00:04:29
21  Alarm 12_START 2021-05-06 02:47:22+00:00 0 days 00:04:25
22  Alarm 13_START 2021-05-06 02:47:22+00:00 0 days 00:04:25
23  Alarm 14_START 2021-05-06 02:49:33+00:00 0 days 00:05:58
24    Alarm 12_END 2021-05-06 02:51:47+00:00 0 days 00:04:25
25    Alarm 13_END 2021-05-06 02:51:47+00:00 0 days 00:04:25
26    Alarm 14_END 2021-05-06 02:55:31+00:00 0 days 00:05:58
27  Alarm 15_START 2021-05-06 04:38:07+00:00 0 days 00:00:18
28    Alarm 15_END 2021-05-06 04:38:25+00:00 0 days 00:00:18
29     Alarm 9_END 2021-05-06 04:59:54+00:00 0 days 03:01:29
30     Alarm 8_END 2021-05-06 04:59:58+00:00 0 days 03:11:07

In [233]:
np.sum(data["Slice_duration"][:5])

Timedelta('0 days 00:06:04')

In [231]:
# a = []

# for i in range(1,len(data)):
#     for j in range(1, len(data_algo)):
#         if np.sum(data["Slice_duration"][:i])<= data_algo["delta_time"][j] :
#             a += [i * ("A "+ str(j))]
#     #a.append("A1" for i in range(1,6))

In [290]:
s1_start = data_algo['TSTART'].min()
s2_start = s1_start+ data["Slice_duration"][1]
print(s1_start)
print(s2_start)
print(data_algo["TSTART"] >= s1_start)
print(data_algo["TEND"] < s2_start)
data_algo[data_algo["TSTART"] >= s1_start] [data_algo["TEND"] < s2_start]

2021-05-06 01:12:12+00:00
2021-05-06 01:12:16+00:00
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
Name: TSTART, dtype: bool
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
Name: TEND, dtype: bool

ValueError: Unable to coerce list of <class 'pandas.core.series.Series'> to Series/DataFrame

In [92]:
len(x)

25

In [93]:
np.cumsum(x)

array([Timedelta('0 days 00:00:04'), Timedelta('0 days 00:01:06'),
       Timedelta('0 days 00:03:16'), Timedelta('0 days 00:06:00'),
       Timedelta('0 days 00:06:04'), Timedelta('0 days 00:09:11'),
       Timedelta('0 days 00:15:13'), Timedelta('0 days 00:29:26'),
       Timedelta('0 days 00:30:53'), Timedelta('0 days 00:34:00'),
       Timedelta('0 days 00:35:23'), Timedelta('0 days 00:36:39'),
       Timedelta('0 days 00:46:13'), Timedelta('0 days 01:10:15'),
       Timedelta('0 days 01:10:36'), Timedelta('0 days 01:11:22'),
       Timedelta('0 days 01:14:44'), Timedelta('0 days 01:35:10'),
       Timedelta('0 days 01:37:21'), Timedelta('0 days 01:39:35'),
       Timedelta('0 days 01:43:19'), Timedelta('0 days 03:25:55'),
       Timedelta('0 days 03:26:13'), Timedelta('0 days 03:47:42'),
       Timedelta('0 days 03:47:46')], dtype=object)

### Creation de la colonne qui compte le nombre d'alarmes dans chaque slice :

In [274]:
s

        slice_name                      Time        duration
1    Alarm 1_START 2021-05-06 01:12:12+00:00 0 days 00:06:04
2    Alarm 2_START 2021-05-06 01:12:12+00:00 0 days 00:06:04
3    Alarm 3_START 2021-05-06 01:12:16+00:00 0 days 00:05:56
4    Alarm 4_START 2021-05-06 01:13:18+00:00 0 days 00:08:05
5    Alarm 5_START 2021-05-06 01:15:28+00:00 0 days 00:30:44
6      Alarm 3_END 2021-05-06 01:18:12+00:00 0 days 00:05:56
7      Alarm 1_END 2021-05-06 01:18:16+00:00 0 days 00:06:04
8      Alarm 2_END 2021-05-06 01:18:16+00:00 0 days 00:06:04
9      Alarm 4_END 2021-05-06 01:21:23+00:00 0 days 00:08:05
10   Alarm 6_START 2021-05-06 01:27:25+00:00 0 days 00:15:40
11   Alarm 7_START 2021-05-06 01:41:38+00:00 0 days 00:05:57
12     Alarm 6_END 2021-05-06 01:43:05+00:00 0 days 00:15:40
13     Alarm 5_END 2021-05-06 01:46:12+00:00 0 days 00:30:44
14     Alarm 7_END 2021-05-06 01:47:35+00:00 0 days 00:05:57
15   Alarm 8_START 2021-05-06 01:48:51+00:00 0 days 03:11:07
16   Alarm 9_START 2021-05-06 01:58:25+00:00 0 days 03:01:29
17  Alarm 10_START 2021-05-06 02:22:27+00:00 0 days 00:04:29
18  Alarm 11_START 2021-05-06 02:22:48+00:00 0 days 00:00:46
19    Alarm 11_END 2021-05-06 02:23:34+00:00 0 days 00:00:46
20    Alarm 10_END 2021-05-06 02:26:56+00:00 0 days 00:04:29
21  Alarm 12_START 2021-05-06 02:47:22+00:00 0 days 00:04:25
22  Alarm 13_START 2021-05-06 02:47:22+00:00 0 days 00:04:25
23  Alarm 14_START 2021-05-06 02:49:33+00:00 0 days 00:05:58
24    Alarm 12_END 2021-05-06 02:51:47+00:00 0 days 00:04:25
25    Alarm 13_END 2021-05-06 02:51:47+00:00 0 days 00:04:25
26    Alarm 14_END 2021-05-06 02:55:31+00:00 0 days 00:05:58
27  Alarm 15_START 2021-05-06 04:38:07+00:00 0 days 00:00:18
28    Alarm 15_END 2021-05-06 04:38:25+00:00 0 days 00:00:18
29     Alarm 9_END 2021-05-06 04:59:54+00:00 0 days 03:01:29
30     Alarm 8_END 2021-05-06 04:59:58+00:00 0 days 03:11:07

In [38]:
t= []
slice_nb = []
for i in range(1,len(s)):
    t.append(s["Time"][i]- s["Time"][i-1])
    #print("t=", t,"\n somme t = ",np.sum(t))
    if s["Time"][i] != s["Time"][i-1] : #  and  np.sum(t) >= s["duration"][i] :
        slice_nb.append("S " + str(i)+ ": " + str(i+1))
    else : 
        slice_nb.append("S " + str(i)+ ": " + str(i+1))

In [39]:
slice_nb

['S 1: 2',
 'S 2: 3',
 'S 3: 4',
 'S 4: 5',
 'S 5: 6',
 'S 6: 7',
 'S 7: 8',
 'S 8: 9',
 'S 9: 10',
 'S 10: 11',
 'S 11: 12',
 'S 12: 13',
 'S 13: 14',
 'S 14: 15',
 'S 15: 16',
 'S 16: 17',
 'S 17: 18',
 'S 18: 19',
 'S 19: 20',
 'S 20: 21',
 'S 21: 22',
 'S 22: 23',
 'S 23: 24',
 'S 24: 25',
 'S 25: 26',
 'S 26: 27',
 'S 27: 28',
 'S 28: 29',
 'S 29: 30']

In [ ]:
t[0] + t[1]+t[2]+t[3] + t[4]#+t[5]#+t[6]+ t[7]

In [ ]:
#t_df = pd.DataFrame({"_time": t})
#s2 = pd.concat([s,t_df], axis = 1)
#s2

In [294]:
data["Slice_duration"][1]

Timedelta('0 days 00:00:04')

In [299]:
t= []
slice_nb = []
for i in range(1,len(data)):
    for j in range(1,len(s)): 
        
        t.append(data["Slice_duration"][i])
        print("t=", t,"\n somme t = ",np.sum(t))
    
        if s["Time"][i] != s["Time"][i-1]  and  np.sum(t) >= data["Slice_duration"][i] :
            slice_nb.append("S " + str(i)+ ": " + str(i+1))
    #else : 
        #slice_nb.append("S " + str(i)+ ": " + str(i+1))

t= [Timedelta('0 days 00:00:04')]
 somme t =  0 days 00:00:04

KeyError: 0

In [300]:
s

        slice_name                      Time        duration
1    Alarm 1_START 2021-05-06 01:12:12+00:00 0 days 00:06:04
2    Alarm 2_START 2021-05-06 01:12:12+00:00 0 days 00:06:04
3    Alarm 3_START 2021-05-06 01:12:16+00:00 0 days 00:05:56
4    Alarm 4_START 2021-05-06 01:13:18+00:00 0 days 00:08:05
5    Alarm 5_START 2021-05-06 01:15:28+00:00 0 days 00:30:44
6      Alarm 3_END 2021-05-06 01:18:12+00:00 0 days 00:05:56
7      Alarm 1_END 2021-05-06 01:18:16+00:00 0 days 00:06:04
8      Alarm 2_END 2021-05-06 01:18:16+00:00 0 days 00:06:04
9      Alarm 4_END 2021-05-06 01:21:23+00:00 0 days 00:08:05
10   Alarm 6_START 2021-05-06 01:27:25+00:00 0 days 00:15:40
11   Alarm 7_START 2021-05-06 01:41:38+00:00 0 days 00:05:57
12     Alarm 6_END 2021-05-06 01:43:05+00:00 0 days 00:15:40
13     Alarm 5_END 2021-05-06 01:46:12+00:00 0 days 00:30:44
14     Alarm 7_END 2021-05-06 01:47:35+00:00 0 days 00:05:57
15   Alarm 8_START 2021-05-06 01:48:51+00:00 0 days 03:11:07
16   Alarm 9_START 2021-05-06 01:58:25+00:00 0 days 03:01:29
17  Alarm 10_START 2021-05-06 02:22:27+00:00 0 days 00:04:29
18  Alarm 11_START 2021-05-06 02:22:48+00:00 0 days 00:00:46
19    Alarm 11_END 2021-05-06 02:23:34+00:00 0 days 00:00:46
20    Alarm 10_END 2021-05-06 02:26:56+00:00 0 days 00:04:29
21  Alarm 12_START 2021-05-06 02:47:22+00:00 0 days 00:04:25
22  Alarm 13_START 2021-05-06 02:47:22+00:00 0 days 00:04:25
23  Alarm 14_START 2021-05-06 02:49:33+00:00 0 days 00:05:58
24    Alarm 12_END 2021-05-06 02:51:47+00:00 0 days 00:04:25
25    Alarm 13_END 2021-05-06 02:51:47+00:00 0 days 00:04:25
26    Alarm 14_END 2021-05-06 02:55:31+00:00 0 days 00:05:58
27  Alarm 15_START 2021-05-06 04:38:07+00:00 0 days 00:00:18
28    Alarm 15_END 2021-05-06 04:38:25+00:00 0 days 00:00:18
29     Alarm 9_END 2021-05-06 04:59:54+00:00 0 days 03:01:29
30     Alarm 8_END 2021-05-06 04:59:58+00:00 0 days 03:11:07

In [301]:
data

   Slices  Slice_duration
1     S 1 0 days 00:00:04
2     S 2 0 days 00:01:02
3     S 3 0 days 00:02:10
4     S 4 0 days 00:02:44
5     S 5 0 days 00:00:04
6     S 6 0 days 00:03:07
7     S 7 0 days 00:06:02
8     S 8 0 days 00:14:13
9     S 9 0 days 00:01:27
10   S 10 0 days 00:03:07
11   S 11 0 days 00:01:23
12   S 12 0 days 00:01:16
13   S 13 0 days 00:09:34
14   S 14 0 days 00:24:02
15   S 15 0 days 00:00:21
16   S 16 0 days 00:00:46
17   S 17 0 days 00:03:22
18   S 18 0 days 00:20:26
19   S 19 0 days 00:02:11
20   S 20 0 days 00:02:14
21   S 21 0 days 00:03:44
22   S 22 0 days 01:42:36
23   S 23 0 days 00:00:18
24   S 24 0 days 00:21:29
25   S 25 0 days 00:00:04

In [302]:
data_algo

,BTAVAILABILITYLOGSID,MESSAGE,TSTART,TEND,Alarm_number,delta_time
1,2060070,Battery Charger Failure Cleared,2021-05-06 01:12:12+00:00,2021-05-06 01:18:16+00:00,Alarm 1,0 days 00:06:04
2,2060069,LVPS Line Failure Cleared,2021-05-06 01:12:12+00:00,2021-05-06 01:18:16+00:00,Alarm 2,0 days 00:06:04
3,2060076,LVPS Line Failure Cleared,2021-05-06 01:12:16+00:00,2021-05-06 01:18:12+00:00,Alarm 3,0 days 00:05:56
4,2059912,Train in Full Manual Mode Cleared,2021-05-06 01:13:18+00:00,2021-05-06 01:21:23+00:00,Alarm 4,0 days 00:08:05
5,2058722,Emergency Brake Trainline Deenergized VATC Cle...,2021-05-06 01:15:28+00:00,2021-05-06 01:46:12+00:00,Alarm 5,0 days 00:30:44
6,2058899,Inaccurate Station Stop Short Cleared,2021-05-06 01:27:25+00:00,2021-05-06 01:43:05+00:00,Alarm 6,0 days 00:15:40
7,2058641,Train Failed to Arrive Cleared,2021-05-06 01:41:38+00:00,2021-05-06 01:47:35+00:00,Alarm 7,0 days 00:05:57
8,2053623,Emergency Brake Trainline Deenergized VATC Cle...,2021-05-06 01:48:51+00:00,2021-05-06 04:59:58+00:00,Alarm 8,0 days 03:11:07
9,2053629,Inaccurate Station Stop Short Cleared,2021-05-06 01:58:25+00:00,2021-05-06 04:59:54+00:00,Alarm 9,0 days 03:01:29
10,2057424,Train Failed to Arrive Cleared,2021-05-06 02:22:27+00:00,2021-05-06 02:26:56+00:00,Alarm 10,0 days 00:04:29
11,2057503,Unscheduled Stop Cleared,2021-05-06 02:22:48+00:00,2021-05-06 02:23:34+00:00,Alarm 11,0 days 00:00:46
12,2056902,Battery Charger Failure Cleared,2021-05-06 02:47:22+00:00,2021-05-06 02:51:47+00:00,Alarm 12,0 days 00:04:25
13,2056901,LVPS Line Failure Cleared,2021-05-06 02:47:22+00:00,2021-05-06 02:51:47+00:00,Alarm 13,0 days 00:04:25
14,2056759,Summary Doors Failed to Close Cleared,2021-05-06 02:49:33+00:00,2021-05-06 02:55:31+00:00,Alarm 14,0 days 00:05:58
15,2054139,Unscheduled Stop Cleared,2021-05-06 04:38:07+00:00,2021-05-06 04:38:25+00:00,Alarm 15,0 days 00:00:18

In [ ]:

# def add_slices(row):

#     slices[row['TSTART']] = row['Alarm_number'] +'_START'

#     slices[row['TEND']] = row['Alarm_number'] +'_END'
    
# data_algo.apply(add_slices,axis = 1)

# slices